Blog/urls.py
from django.urls import path

from Blog import views
from Blog.views import *

urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
    path('blog/post/', CreatePostView.as_view(), name='post'),
    path('blog/cuprins/',FullPostList.as_view(), name='cuprins_blog'),
    path('blog/lista-calatorii/',PostListCalatorii.as_view(), name='lista_calatorii'),
    path('blog/lista-carti/',PostListCarti.as_view(), name='lista_carti'),
    path('blog/search/',SearchResultView.as_view(), name='search_blog'),
    path('blog/despre/', show_despre_mine_page, name='despre_mine'),
    path('blog/contact/', show_contact_page, name='contact'),
    path('blog/tag-select/<str:tag>',PostListTag.as_view(), name='tag_select_list'),
    path('blog/tag-select-check/',PostListTag.as_view(), name='tag_select_list_check'),
    path('blog/share/<str:social>/<str:id>', share_on_media, name="share_on_media"),
    # path('blog/share-whatsapp/<str:id>', share_on_whatsapp_func, name="share_on_whatsapp"),
    # path('blog/despre/', DespreMine.as_view(), name='despre_mine'),
    # path('<slug:slug>/', views.post_details, name='post_detail'),
    path('blog/comment/<slug:slug>', views.AddCommentView.as_view(), name='add_comment'),
    path('blog/send-newsletter/<slug:slug>', new_post_newsletter, name='send_newsletter')
]

djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include
from requests import post

from Blog.views import CreatePostView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('Blog.urls')),
    path('', include('newsletter.urls')),

]

newsletter/urls.py
from django.urls import path
from .views import newsletter_subscribe, show_subscription

app_name = 'newsletter'
urlpatterns = [
      path('newsletter/subscribe/', newsletter_subscribe, name='subscribe'),
      path('newsletter/subscription-done/', show_subscription, name='subscription_done'),

]

newsletter/models.py
from django.db import models
from django.core.validators import MinLengthValidator
class NewsUsers(models.Model):
    name = models.CharField(max_length = 60, blank=False, null=False)
    email = models.EmailField(blank=False,null=False)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name = "NewsUser"
        verbose_name_plural = "NewsUsers"

    def __str__(self):
        return self.email

newsletter/forms.py
from django import forms
from django.forms import TextInput, EmailInput
from django.shortcuts import render

from .models import NewsUsers
class NewsUserForm(forms.ModelForm):
    class Meta:
        model = NewsUsers
        fields = ['name', 'email']

        widgets = {
            'name': TextInput(attrs={'placeholder': 'Please enter your first name', 'class': 'form-control'}),
            'email': EmailInput(attrs={'placeholder': 'Please enter your email', 'class': 'form-control'}),
        }

    def clean(self):
        cleaned_data = self.cleaned_data
        users = NewsUsers.objects.all()
        for user in users:
            if cleaned_data.get('email') == NewsUsers.email:
                msg = ' adresa de email exista deja'
                self._errors['email'] = self.error_class([msg])

        return cleaned_data

newsletter/views.py
from django.contrib import messages
from django.shortcuts import render

from Blog.views import CreatePostView
from newsletter import forms
from newsletter.forms import NewsUserForm
from newsletter.models import NewsUsers
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.conf import settings
from django.core.mail import send_mail


def newsletter_subscribe(request):
    global instance
    if request.method == 'POST':
        form = NewsUserForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            if NewsUsers.objects.filter(email=instance.email).exists():
                print('Aceasta adresa de email exista deja')
                return render(request, "newsletter/subscribe.html")
            else:

                # daca e spatiu gol, nu trimite mail
                instance.save()
                print("mail adaugat")
                newUsers = NewsUsers.objects.all()
                print(newUsers)
                firstUser = newUsers[0]
                print(firstUser)
                lastUser = newUsers[len(newUsers) - 1]
                print(lastUser)
                email = lastUser.email

                send_mail(
                    subject="Test 1",
                    message="Hey, te-ai inregistrat!",
                    from_email=settings.EMAIL_HOST_USER,
                    recipient_list=[email]
                )

        return render(request, "newsletter/subscribe.html")
    else:
        form = NewsUserForm()

    context = {'form': form}
    template = "newsletter/subscribe.html"
    return render(request, template, context)


def show_subscription(request):
    return render(request, "newsletter/subscription_done.html")

# def new_post_newsletter(request):
#      if request.method == 'POST':
#         form = NewsUserForm(request.POST)
#         if 'newsletter_sub' in request.POST:
#              newUsers = NewsUsers.objects.all()
#              print(newUsers)
#               for newUser in newUsers:
#                 email = newUser.email
#                 send_mail(
#                   subject="Test 1",
#                   message="Hey, am postat ceva nou",
#                   from_email=settings.EMAIL_HOST_USER,
#                   recipient_list=[email]
#                 )
#
#     context = {'form': form}
#     template = "newsletter/subscribe.html"
#     return render(request, template, context)

newsletter/templates/newsletter/subscribe.html
{#{% extends "base.html" %}#}
{#{% block content %}#}
{#<form action="{% url 'newsletter:subscribe' %}" method="post">#}
{#{% csrf_token %}#}
{#{{ form.as_p }}#}
{#<button type="submit">Adauga</button>#}
{#</form>#}
{#{% endblock %}#}
{% extends 'base.html' %}

<br>

{% block content %}
    <footer class="footer-color text-center footer-text">
        <div class="container p-4">

                <section class="">
                    <form action="{% url 'newsletter:subscribe' %}" method="post">
                        <div class="row d-flex justify-content-center">
                            {% csrf_token %}

                            <div class="col-auto">
                                <p class="pt-2">Abonare newsletter:</p>
                            </div>

                            <div class="col-auto">
                                <input id="name" name="name" class="form-control" placeholder="Introdu numele"/>
                            </div>

                            <div class="col-auto">
                                <input id="email" name="email" type="email" class="form-control"
                                       placeholder="Introdu adresa de e-mail:"/>
                            </div>

                            <div class="col-auto">
                                <button type="submit">Adaugă</button>
                                 <a href="{% url 'newsletter:subscription_done' %}" class="btn btn-primary btn-lg active" role="button"
                       aria-pressed="true" >Adauga_link</a>
                            </div>
                        </div>
                    </form>
                </section>

        </div>
    </footer>
{% endblock %}

newsletter/templates/newsletter/subscription_done.html
{% extends 'base.html ' %}

{% block title %} Newsletter inregistrat {% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">
                    <h3 class="text-center">V-aţi înregistrat cu succes la newsletter.</h3>
                </div>
                    <div class="card-body">
                       <h3 class="text-center"> Vă mulţumesc.</h3>
                    </div>
                    <div class="card-footer text-center">
                      <a href="{% url 'home' %}"class="btn btn-outline-secondary">Home</a>
                    </div>

            </div>
        </div>
    </div>
</div>

{% endblock %}