Blog/urls.py
from django.urls import path

from Blog import views
from Blog.views import *

urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
    path('blog/post/', CreatePostView.as_view(), name='post'),
    path('blog/cuprins/',FullPostList.as_view(), name='cuprins_blog'),
    path('blog/lista-calatorii/',PostListCalatorii.as_view(), name='lista_calatorii'),
    path('blog/lista-carti/',PostListCarti.as_view(), name='lista_carti'),
    path('blog/search/',SearchResultView.as_view(), name='search_blog'),
    path('blog/despre/', show_despre_mine_page, name='despre_mine'),
    path('blog/contact/', show_contact_page, name='contact'),
    path('blog/tag-select/<str:tag>',PostListTag.as_view(), name='tag_select_list'),
    path('blog/tag-select-check/',PostListTag.as_view(), name='tag_select_list_check'),
    path('blog/share/<str:social>/<str:id>', share_on_media, name="share_on_media"),
    # path('blog/share-whatsapp/<str:id>', share_on_whatsapp_func, name="share_on_whatsapp"),
    # path('blog/despre/', DespreMine.as_view(), name='despre_mine'),
    # path('<slug:slug>/', views.post_details, name='post_detail'),
    path('blog/comment/<slug:slug>', views.AddCommentView.as_view(), name='add_comment'),
    path('blog/send-newsletter/<slug:slug>', new_post_newsletter, name='send_newsletter')
]

djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include
from requests import post

from Blog.views import CreatePostView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('Blog.urls')),
    path('', include('newsletter.urls')),

]

newsletter/urls.py
from django.urls import path
from .views import newsletter_subscribe, show_subscription

app_name = 'newsletter'
urlpatterns = [
      path('newsletter/subscribe/', newsletter_subscribe, name='subscribe'),
      path('newsletter/subscription-done/', show_subscription, name='subscription_done'),

]

Blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Model
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField, CKEditorWidget
from tinymce.models import HTMLField
from django.utils.html import strip_tags
STATUS = (
    (0, "Draft"),
    (1, "Publish")
)


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now=True)
    content = RichTextField(blank=True, null=True, config_name='awesome_ckeditor')

    category = models.CharField(max_length=200, default='calatorii')
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    tags = models.CharField(max_length=200, null=True, default="")

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title
class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

templates/add_comment.html
{% extends 'base.html' %}
{% block title %} Comentarii
{% endblock %}
{% block content %}
            {% if new_comment %}

          <p>Comentariul tau asteapta sa fie inscris</p>

        {% else %}
    <h1>Adauga comentariu</h1>
    <br><br>
    <div class="form-group">
    <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
        <button class="btn btn-secondary" name = "send_comment">Adauga comentariul</button>

    </form>
            {% endif %}
    </div>






{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Django Central</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
    <meta name="google" content="notranslate"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{%  static '/css/my_style.css' %}">
</head>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>


<body>
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 17px;
        background-color: #fdfdfd;
    }

    .shadow {
        box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
    }

    .btn-danger {
        color: #fff;
        background-color: #f00000;
        border-color: #dc281e;
    }

    .masthead {
        background: #3398E1;
        height: auto;
        padding-bottom: 15px;
        box-shadow: 0 16px 48px #E3E7EB;
        padding-top: 10px;
    }
</style>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Home</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                {% if perms.blog.view_post %}
                <li class="nav-item text-black">
                    <a class="nav-link text-black font-weight-bold" href="{% url 'post' %}">Adauga postare</a>
                </li>
                {% endif %}
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1"
                            data-bs-toggle="dropdown" aria-expanded="false">
                        Dropdown button
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        <li><a class="dropdown-item" href="{% url 'lista_calatorii' %}">Călătorii</a></li>
                        <li><a class="dropdown-item" href="{% url 'lista_carti' %}">Cărţi</a></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </div>
                <li class="nav-item text-black">
                    <a class="nav-link text-black font-weight-bold" href="{% url 'despre_mine' %}">Despre mine</a>
                </li>
             <li class="nav-item text-black">
                    <a class="nav-link text-black font-weight-bold" href="{% url 'newsletter:subscribe' %}">Abonare newsletter</a>
                </li>
                  <li class="nav-item text-black">
                    <a class="nav-link text-black font-weight-bold" href="{% url 'contact' %}">Contact</a>
                </li>
                 <li class="nav-item text-black">
                    <a class="nav-link text-black font-weight-bold" href="{% url 'cuprins_blog' %}">Ce conţine blogul?</a>
                </li>
                <form action ="{% url 'search_blog' %}" method= "GET" class="d-flex" role="search">
                    {% csrf_token %}
                    <input name= "query"  class="form-control me-2" type="text" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </ul>
        </div>
    </div>
</nav>
{% block content %}
    <!-- Content Goes here -->
{% endblock content %}
<!-- Footer -->
<footer class="py-3 bg-grey">
    <p class="m-0 text-dark text-center ">Copyright &copy; Ioan Eduard</p>
</footer>
</body>
<script src="{%  static 'js/my_script.js' %}"></script>
</html>

templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/cuprins_blog.html
{% extends "base.html" %}
{% load static %}
{% load customs %}

{% block content %}
<br>
<br>
<body>
<ul class="menu">
{% for post in post_list %}

<li><a href="{% url 'post_detail' post.slug %}"> {{ post.title }}</a></li>

{% endfor %}
</ul>



</body>
{% endblock %}

templates/despre_mine.html
{% extends "base.html" %}
{% load static %}
{% load customs %}

{% block content %}

    <header>


        <h1 style="text-align:center;font-size:60px;"> Despre mine</h1>
        <div class="flex-container">>
            <div class="col-md-8">
                <img style="width: 600px;display: block;  margin-left: auto;  margin-right: auto; "
                     alt="Gradina japoneza"
                     src="{% static 'images/poza_baza.jpg' %}"/>
            </div>
            <div class="col-md-6">
                <div class="container">
                    <p style="text-align: justify">
                        Ioan Eduard, ghid de turism
                        <br>începând din anul 2005.
                        Până<br> în prezent am condus peste
                        <br> 150 de circuite în toate
                        <br> colţurile lumii.
                    </p>
                    <p>
                        Am străbătut Europa de la Capul Nord până în Insula Creta şi din Irlanda până la Munţii Urali.
                        M-au
                        atras dintotdeauna Orientul Apropiat, Asia Centrală şi Drumul Mătăsii, mă simt acasă în Orientul
                        Îndepărtat, dar inima îmi bate întotdeauna mai cu putere când mă gândesc la Japonia, de al cărei
                        miraj mă simt irezistibil atras.


                    </p>
                </div>
            </div>
        </div>
    </header>
{#    <div class=flex-container>#}
{#        <div>#}
{#            <h1>Checkbox</h1>#}
{##}
{#            <form action="{% url 'tag_select_list_check'  %}" >#}
{#                {% for item in post.tags|string_to_list %}#}
{#                    <a href="{% url "tag_select_list" tag=item %}"> {{ item }}</a></p>#}
{#                {% endfor %}#}
{#                <input type="checkbox" id="vehicle1" name="vehicle1" value="Bike">#}
{#                <label for="vehicle1"> I have a bike</label><br>#}
{#                <input type="checkbox" id="vehicle2" name="vehicle2" value="Car">#}
{#                <label for="vehicle2"> I have a car</label><br>#}
{#                <input type="checkbox" id="vehicle3" name="vehicle3" value="Boat">#}
{#                <label for="vehicle3"> I have a boat</label><br><br>#}
{#                <input type="submit" value="Submit" >#}
{#            </form>#}
{##}
{#        </div>#}
{#    </div>#}
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load customs %}
{% load static %}
{% block content %}

    <header>
<br>
<br>

        <h1 style="text-align:center;font-size:60px;"> Fărâme de lume</h1>
        <div class="flex-container">>
            <div class="col-md-10">
                <img style="width: 1024px;display: block;  margin-left: auto;  margin-right: auto; "
                     alt="Gradina japoneza"
                     src="{% static 'images/poza_baza.jpg' %}"/>
            </div>
            <div class="col-md-1">
                <div class="sidenav">
                    <a href="{% url 'cuprins_blog' %}" class="btn btn-primary btn-lg active" role="button"
                       aria-pressed="true">Ce conţine blogul?</a>
                    {#                    {% for post in post_list|slice:":10" %}#}
                    {#                        <a href="{% url 'post_detail' post.slug %}"> {{ post.title }}</a>#}
                    {#                    {% endfor %}#}

                </div>
                <div class=flex-container>
                    <div>
                        <h4 style="text-justify:auto ">Căutare după taguri.</h4>

                        <form action="{% url 'tag_select_list_check' %}">
                            {% for item in post_list|extract_unique_tags_from_post %}
                                <input type="checkbox" id="ckb" name="tag" value={{ item }}>
                                <label for="ckb" style="color: maroon"> {{ item }} </label><br>
                            {% endfor %}
                            <input type="submit" value="Caută" class="btn btn-primary btn-lg active" >
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="container-fluid">

        <div class="row">
            {% for post in post_list|slice:":3" %}
                <div class="col-md-4">

                    <div class="card">

                        <div class="card-body">

                            <h2 class="card-title">{{ post.title }}</h2>
                            <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on }}
                                | {{ post.tags }}    </p>
                            <p class="card-text">{{ post.content|striptags|safe|slice:":100" }}</p>
                            <a href="{% url 'post_detail' post.slug %}" class="btn btn-primary">Vezi mai mult &rarr;</a>

                        </div>

                    </div>

                </div>
            {% endfor %}
        </div>
    </div>


{% endblock %}

templates/lista_calatorii.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <header>
<br>
<br>

        <h1 style="text-align:center;font-size:60px;"> Călătorii</h1>
        <div class="flex-container">>
            <div class="col-md-10">
                <img style="width: 1024px;display: block;  margin-left: auto;  margin-right: auto; "
                     alt="Gradina japoneza"
                     src="{% static 'images/poza_baza.jpg' %}"/>
            </div>
            <div class="col-md-1">
                <div class="sidenav">
                <a href="{% url 'cuprins_blog' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Ce conţine blogul?</a>


                </div>
            </div>
        </div>
    </header>
    <div class="container-fluid">

        <div class="row">
            {% for post in post_list|slice:":10" %}
                <div class="col-md-4">

                    <div class="card">

                        <div class="card-body">

                            <h2 class="card-title">{{ post.title }}</h2>
                            <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on }} </p>
                            <p class="card-text">{{ post.content|striptags|safe|slice:":100" }}</p>
                            <a href="{% url 'post_detail' post.slug %}" class="btn btn-primary">Vezi mai mult &rarr;</a>

                        </div>

                    </div>

                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/lista_carti.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <header>
<br>
<br>

        <h1 style="text-align:center;font-size:60px;"> Cărţi </h1>
        <div class="flex-container">>
            <div class="col-md-10">
                <img style="width: 1024px;display: block;  margin-left: auto;  margin-right: auto; "
                     alt="Gradina japoneza"
                     src="{% static 'images/poza_carti.jpg' %}"/>
            </div>
            <div class="col-md-1">
                <div class="sidenav">
                <a href="{% url 'cuprins_blog' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Ce conţine blogul?</a>
{#                    {% for post in post_list|slice:":10" %}#}
{#                        <a href="{% url 'post_detail' post.slug %}"> {{ post.title }}</a>#}
{#                    {% endfor %}#}

                </div>
            </div>
        </div>
    </header>
    <div class="container-fluid">

        <div class="row">
            {% for post in post_list|slice:":10" %}
                <div class="col-md-4">

                    <div class="card">

                        <div class="card-body">

                            <h2 class="card-title">{{ post.title }}</h2>
                            <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on }} </p>
                            <p class="card-text">{{ post.content|striptags|safe|slice:":100" }}</p>
                            <a href="{% url 'post_detail' post.slug %}" class="btn btn-primary">Vezi mai mult &rarr;</a>

                        </div>

                    </div>

                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/post.html
<h1>Creare postare noua</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media}}
    {{ form.as_p }}
    <button type="submit">Adauga noua postare</button>
</form>

templates/post_detail.html
{% extends 'base.html' %}
{% load customs %}
{% load static %}
{% block content %}
    {% load social_share %}
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <div class="card-body">
                    <h1 style="text-align:justify;">{% block title %} {{ object.title }} {% endblock title %}</h1>
                    <p class=" text-muted">{{ post.author }} | {{ post.created_on }} |

                        {% for item in post.tags|string_to_list %}
                            <a href="{% url "tag_select_list" tag=item %}"> {{ item }}</a></p>
                        {% endfor %}

                        <a href="{% url 'share_on_media' social=1 id=post.title %}"><img src="{% static 'images/facebook.png' %}"></a>
                        <a href="{% url 'share_on_media' social=2 id=post.title %}"><img src="{% static 'images/whatsapp.png' %}"></a>

                    <p style="text-align:justify;font-size:50px;">{{ object.content | safe }}</p>
                <div>

            <form action="{% url 'send_newsletter' post.slug %}" method="POST">
                 {% csrf_token %}
                <input type="submit" name="newsletter_sub" value="Subscribe" />
            </form>

                </div>
                </div>
            </div>

        </div>
    </div>



  <div class="col-md-8 card mb-4  mt-3 ">

    <div class="card-body">
    <h2> &nbsp; &nbsp;  Comentarii..</h2>
{% if not post.comments.all %}
    No comments yet <a href="#"> Add one</a>
{% else %}


        {% for comment in post.comments.all %}
        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold">
            {{ comment.name }}
            <span class=" text-muted font-weight-normal">
              {{ comment.created_on }}
            </span>
          </p>
          {{ comment.body | linebreaks }}
        </div>
        {% endfor %}
  {% endif %}
    <br><br>
    <a href="{% url 'add_comment' post.slug %}"> &nbsp; &nbsp;Adauga comentariu nou</a>
      </div>
    </div>

{% endblock content %}

templates/search_blog.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <header>


        <h1 style="text-align:center;font-size:60px;"> Fărâme de lume</h1>
        <div class="flex-container">>
            <div class="col-md-10">
                <img style="width: 1024px;display: block;  margin-left: auto;  margin-right: auto; "
                     alt="Gradina japoneza"
                     src="{% static 'images/poza_baza.jpg' %}"/>
            </div>
            <div class="col-md-1">
                <div class="sidenav">
                    <a href="{% url 'cuprins_blog' %}" class="btn btn-primary btn-lg active" role="button"
                       aria-pressed="true">Ce conţine blogul?</a>

                </div>
            </div>
        </div>
    </header>
    <div class="container-fluid">
    <div class="container my-3">
        <h2>Rezultatele căutării: </h2>
        {% if object_list|length < 1 %}
            <p>Nu am găsit rezultate.</p>
            Căutarea : <b>{{ query }}</b> nu s-a potrivit cu nicio postare. <br>
            Sugestii:
            <ul>
                <li>Verifică dacă ai scris corect cuvintele.</li>
                <li>Caută cuvinte mai generale.</li>
                <li> Introdu mai puţine cuvinte.</li>
                <li> Caută alte cuvinte.</li>

            </ul>

        {% endif %}
    </div>
        <div class="row">
            {% for post in object_list %}
                <div class="col-md-4">

                    <div class="card">

                        <div class="card-body">

                            <h2 class="card-title">{{ post.title }}</h2>
                            <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on }}
                                | {{ post.tags }}    </p>
                            <p class="card-text">{{ post.content|striptags|safe|slice:":100" }}</p>
                            <a href="{% url 'post_detail' post.slug %}" class="btn btn-primary">Vezi mai mult &rarr;</a>

                        </div>

                    </div>

                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/sidebar.html
{#{% block sidebar %}#}
{##}
{#<style>#}
{#        .card{#}
{#            box-shadow: 0 16px 48px #E3E7EB;#}
{#        }#}
{##}
{#</style>#}
{##}
{#<!-- Sidebar Widgets Column -->#}
{#<div class="col-md-4 float-right ">#}
{#<div class="card my-4">#}
{#        <h5 class="card-header">About Us</h5>#}
{#    <div class="card-body">#}
{#        <p class="card-text"> This awesome blog is made on the top of our Favourite full stack Framework 'Django', follow up the tutorial to learn how we made it..!</p>#}
{#        <a href="https://djangocentral.com/building-a-blog-application-with-django"#}
{#           class="btn btn-danger">Know more!</a>#}
{#    </div>#}
{#</div>#}
{#</div>#}
{##}
{#{% endblock sidebar %}#}

templates/tag_search.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <header>


        <h1 style="text-align:center;font-size:60px;"> Fărâme de lume</h1>
        <div class="flex-container">>
            <div class="col-md-10">
                <img style="width: 1024px;display: block;  margin-left: auto;  margin-right: auto; "
                     alt="Gradina japoneza"
                     src="{% static 'images/poza_baza.jpg' %}"/>
            </div>
            <div class="col-md-1">
                <div class="sidenav">
                    <a href="{% url 'cuprins_blog' %}" class="btn btn-primary btn-lg active" role="button"
                       aria-pressed="true">Ce conţine blogul?</a>

                </div>
            </div>
        </div>
    </header>
    <div class="container-fluid">

        <div class="row">
            {% for post in tag_list %}
                <div class="col-md-4">

                    <div class="card">

                        <div class="card-body">

                            <h2 class="card-title">{{ post.title }}</h2>
                            <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on }}
                                | {{ post.tags }}    </p>
                            <p class="card-text">{{ post.content|striptags|safe|slice:":100" }}</p>
                            <a href="{% url 'post_detail' post.slug %}" class="btn btn-primary">Vezi mai mult &rarr;</a>

                        </div>

                    </div>

                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/tag_select_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <header>


{#        <h1 style="text-align:center;font-size:60px;"> Călătorii</h1>#}
        <div class="flex-container">>
            <div class="col-md-10">
                <img style="width: 1024px;display: block;  margin-left: auto;  margin-right: auto; "
                     alt="Gradina japoneza"
                     src="{% static 'images/poza_baza.jpg' %}"/>
            </div>
            <div class="col-md-1">
                <div class="sidenav">
                <a href="{% url 'cuprins_blog' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Continut blog</a>
{#                    {% for post in post_list|slice:":10" %}#}
{#                        <a href="{% url 'post_detail' post.slug %}"> {{ post.title }}</a>#}
{#                    {% endfor %}#}

                </div>
            </div>
        </div>
    </header>
    <div class="container-fluid">

        <div class="row">
            {% for post in post_list|slice:":10" %}
                <div class="col-md-4">

                    <div class="card">

                        <div class="card-body">

                            <h2 class="card-title">{{ post.title }}</h2>
                            <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on }} </p>
                            <p class="card-text">{{ post.content|striptags|safe|slice:":100" }}</p>
                            <a href="{% url 'post_detail' post.slug %}" class="btn btn-primary">Vezi mai mult &rarr;</a>

                        </div>

                    </div>

                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}